### ISSUE TITLE
Improved Todo

### ISSUE THREAD

**Issue by tzuennn** [chengzihao123/2024-Orbital-6041-StudySphere#12]
- [x] Link to firestore from firebase
- [x] Improve overall UI
- [x] Add in more fields, priority, deadline, status etc
- [x] Sorting and Filter function (Most recent-oldest)
- [x] Colour coding for tasks of different priority
- [x] Handle completed tasks by pushing it to the bottom of the list
- [x] Ensure its only accessible after signed in
